# Project: BBL AI Fantasy v2 
# Section: Pricing Model Build

# 0. Prerequistes

In [120]:
import pandas as pd
import numpy as np
import os

os.getcwd()
directory = 'C:/Users/dilan/OneDrive/Documents/Data Science Projects/Repos/Big-Bash-Fantasy-AI-v2'
directory

'C:/Users/dilan/OneDrive/Documents/Data Science Projects/Repos/Big-Bash-Fantasy-AI-v2'

# 1. Data Extraction

In [121]:
# BBL14 player price (each round)
# Round 1
price_1 = pd.read_csv(os.path.join(directory,'data/prev_season_data/add_data_created/round_1/player_price.csv'), low_memory=False)[['player', 'Price']]
#price_1 = price_1.rename(columns={'Price': 'Price_1'})
price_1['rnd'] = 1

# Round 2
price_2 = pd.read_csv(os.path.join(directory,'data/prev_season_data/add_data_created/round_2/player_price_round_2.csv'), low_memory=False)[['player', 'Price']]
#price_2 = price_2.rename(columns={'Price': 'Price_2'})
price_2['rnd'] = 2

# Round 3
price_3 = pd.read_csv(os.path.join(directory,'data/prev_season_data/add_data_created/round_3/player_price_rnd_3.csv'), low_memory=False)[['player', 'Price']]
#price_3 = price_3.rename(columns={'Price': 'Price_3'})
price_3['rnd'] = 3

# Round 4
price_4 = pd.read_csv(os.path.join(directory,'data/prev_season_data/add_data_created/round_4/player_price_rnd_4.csv'), low_memory=False)[['player', 'Price']]
#price_4 = price_4.rename(columns={'Price': 'Price_4'})
price_4['rnd'] = 4

# Round 5
price_5 = pd.read_csv(os.path.join(directory,'data/prev_season_data/add_data_created/round_5/player_price_rnd_5.csv'), low_memory=False)[['player', 'Price']]
#price_5 = price_5.rename(columns={'Price': 'Price_5'})
price_5['rnd'] = 5

# Round 6
price_6 = pd.read_csv(os.path.join(directory,'data/prev_season_data/add_data_created/round_6/player_price_rnd_6.csv'), low_memory=False)[['player', 'Price']]
#price_6 = price_6.rename(columns={'Price': 'Price_6'})
price_6['rnd'] = 6

# Round 7
price_7 = pd.read_csv(os.path.join(directory,'data/prev_season_data/add_data_created/round_7/player_price_rnd_7.csv'), low_memory=False)[['player', 'Price']]
#price_7 = price_7.rename(columns={'Price': 'Price_7'})
price_7['rnd'] = 7

# Round 8
price_8 = pd.read_csv(os.path.join(directory,'data/prev_season_data/add_data_created/round_8/player_price_rnd_8.csv'), low_memory=False)[['player', 'Price']]
#price_8 = price_8.rename(columns={'Price': 'Price_8'})
price_8['rnd'] = 8

# Round 9
price_9 = pd.read_csv(os.path.join(directory,'data/prev_season_data/add_data_created/round_9/player_price_rnd_9.csv'), low_memory=False)[['player', 'Price']]
#price_9 = price_9.rename(columns={'Price': 'Price_9'})
price_9['rnd'] = 9
print(price_9)

# After Round 9
price_10 = pd.read_csv(os.path.join(directory,'data/prev_season_data/add_data_created/end_of_round_9/player_price_final.csv'), low_memory=False)[['player', 'Price']]
#price_10 = price_10.rename(columns={'Price': 'Price_10'})
price_10['rnd'] = 10
print(price_10)

               player   Price  rnd
0             A Zampa  124300    9
1             AC Agar  156600    9
2            AF Milne  102600    9
3             AI Ross  123900    9
4           AJ Hosein  125500    9
..                ...     ...  ...
144           WA Agar  122500    9
145  Waqar Salamkheil   92200    9
146     Will Salzmann   39500    9
147      Xavier Crone   39500    9
148       XC Bartlett  140100    9

[149 rows x 3 columns]
            player   Price  rnd
0        SA Abbott  150800   10
1          AC Agar  156400   10
2          WA Agar  122500   10
3     Fabian Allen  115700   10
4       Finn Allen  111900   10
..             ...     ...  ...
144       JW Wells   84400   10
145  JD Wildermuth   58500   10
146        JP Wood   73800   10
147       M Wright  126300   10
148        A Zampa  124300   10

[149 rows x 3 columns]

In [122]:
# BBL14 player points
point = pd.read_csv(os.path.join(directory,'data/prev_season_data/add_data_created/end_of_round_9/player_bbl14_pts_final_2425.csv'), low_memory=False)
point.drop(['Price'], axis=1, inplace=True)

In [ ]:
# BBL14 Team Fixture
fix_df = pd.read_csv(os.path.join(directory,'data/prev_season_data/add_data_created/overall/team_fixture.csv'), low_memory=False)

,Team,R1_G1,R1_G2,R2_G1,R2_G2,R3_G1,R3_G2,R4_G1,R4_G2,R5_G1,R5_G2,R6_G1,R6_G2,R7_G1,R7_G2,R8_G1,R8_G2,R9_G1,R9_G2
0,Adelaide Strikers,Sydney Thunder,NaN,Melbourne Stars,Brisbane Heat,Hobart Hurricanes,NaN,Perth Scorchers,Melbourne Renegades,Hobart Hurricanes,NaN,NaN,NaN,Brisbane Heat,NaN,Sydney Sixers,NaN,Perth Scorchers,NaN
1,Melbourne Stars,Perth Scorchers,Brisbane Heat,Adelaide Strikers,NaN,Sydney Sixers,Sydney Thunder,Brisbane Heat,NaN,Melbourne Renegades,NaN,Sydney Sixers,NaN,Melbourne Renegades,NaN,NaN,NaN,Hobart Hurricanes,NaN
2,Sydney Sixers,Melbourne Renegades,NaN,Sydney Thunder,NaN,Melbourne Stars,Brisbane Heat,Hobart Hurricanes,NaN,Brisbane Heat,NaN,Melbourne Stars,NaN,Perth Scorchers,NaN,Adelaide Strikers,NaN,Sydney Thunder,NaN
3,Brisbane Heat,Melbourne Stars,NaN,Adelaide Strikers,NaN,Sydney Sixers,Perth Scorchers,Melbourne Stars,NaN,Sydney Sixers,NaN,Sydney Thunder,NaN,Adelaide Strikers,NaN,Hobart Hurricanes,NaN,Melbourne Renegades,NaN
4,Perth Scorchers,Melbourne Stars,NaN,Hobart Hurricanes,Melbourne Renegades,Brisbane Heat,NaN,Adelaide Strikers,NaN,Sydney Thunder,NaN,Melbourne Renegades,NaN,Sydney Sixers,NaN,Sydney Thunder,NaN,Adelaide Strikers,NaN
5,Sydney Thunder,Adelaide Strikers,NaN,Sydney Sixers,NaN,Melbourne Stars,NaN,Melbourne Renegades,NaN,Perth Scorchers,NaN,Brisbane Heat,Hobart Hurricanes,Hobart Hurricanes,NaN,Perth Scorchers,NaN,Sydney Sixers,NaN
6,Hobart Hurricanes,Melbourne Renegades,NaN,Perth Scorchers,NaN,Adelaide Strikers,NaN,Sydney Sixers,NaN,Adelaide Strikers,NaN,Sydney Thunder,NaN,Sydney Thunder,NaN,Melbourne Renegades,Brisbane Heat,Melbourne Stars,NaN
7,Melbourne Renegades,Sydney Sixers,Hobart Hurricanes,Perth Scorchers,NaN,NaN,NaN,Sydney Thunder,Adelaide Strikers,Melbourne Stars,NaN,Perth Scorchers,NaN,Melbourne Stars,NaN,Hobart Hurricanes,NaN,Brisbane Heat,NaN

# 2. Data Manipulation

In [129]:
# Create Response Variable Table
# Player | Round | Price Delta (Price - Price_rnd-1)
price = pd.concat([price_1,
                  price_2,
                  price_3,
                  price_4,
                  price_5,
                  price_6,
                  price_7,
                  price_8,
                  price_9,
                  price_10])

# price delta loop
price_delta = pd.DataFrame(columns=['player', 'rnd', 'price_delta'])

for i in range(2,11):
    # previous price and current price
    price_pre = price[price['rnd'] == i-1].rename(columns={'Price': 'price_pre'})
    price_curr = price[price['rnd'] == i].rename(columns={'Price': 'price_curr', 'rnd': 'rnd_curr'})

    # join price table and calculate delta
    price_temp = pd.merge(price_pre, price_curr, how = 'left', on = 'player')
    price_temp['price_delta'] = price_temp['price_curr'] - price_temp['price_pre']
    price_temp.drop(columns=['rnd_curr', 'price_curr'],axis=1, inplace=True)

    price_delta = pd.concat([price_delta, price_temp])

price_delta

               player rnd price_delta  price_pre
0           SA Abbott   1        3900   131800.0
1             AC Agar   1        -600   124100.0
2             WA Agar   1           0    99700.0
3          Finn Allen   1      -11300   152000.0
4        Fabian Allen   1       -1800   117500.0
..                ...  ..         ...        ...
144           WA Agar   9           0   122500.0
145  Waqar Salamkheil   9           0    92200.0
146     Will Salzmann   9           0    39500.0
147      Xavier Crone   9           0    39500.0
148       XC Bartlett   9      -18000   140100.0

[1340 rows x 4 columns]

In [128]:
# Game to Round Team Lookup Table
fix_df.fillna(0, inplace=True)
fix_col_list = fix_df.columns.drop(['Team'])

# Create binary columns based on missing values
for col in fix_col_list:
    fix_df[col] = np.where(fix_df[col] == 0, 0, 1)

# Change table from wide to long
rnd_game_df = pd.melt(fix_df, id_vars = 'Team',
                      var_name='rnd', value_name='games')
rnd_game_df['rnd'] = rnd_game_df['rnd'].str[1:2]
rnd_game_df = rnd_game_df.groupby(['Team', 'rnd'])['games'].sum().reset_index()
rnd_game_df['cum_games'] = rnd_game_df.groupby(['Team'])['games'].cumsum()
rnd_game_df.drop(['games'], axis=1, inplace=True)
rnd_game_df.rename(columns={'cum_games':'games'}, inplace=True)
rnd_game_df.sort_values(['rnd','games'], inplace=True)

# Create team games df
total_games = pd.DataFrame(list(range(1,11)))
total_games.rename(columns={total_games.columns[0]:'games'}, inplace=True)
total_games['join'] = 1

teams = pd.DataFrame(fix_df['Team']).copy()
teams['join'] = 1

game_rnd_df = pd.merge(teams, total_games, on = 'join').drop(['join'], axis=1)

# Join round to game table (using fuzzy join)
game_rnd_team_df = pd.merge_asof(game_rnd_df.sort_values('games'), rnd_game_df.sort_values('games'), on = 'games', by='Team', direction='forward')
game_rnd_team_df

                   Team  games rnd
0     Adelaide Strikers      1   1
1       Melbourne Stars      1   1
2         Brisbane Heat      1   1
3         Sydney Sixers      1   1
4        Sydney Thunder      1   1
..                  ...    ...  ..
75        Sydney Sixers     10   9
76      Melbourne Stars     10   9
77    Adelaide Strikers     10   9
78    Hobart Hurricanes     10   9
79  Melbourne Renegades     10   9

[80 rows x 3 columns]

In [ ]:
# Add round column to player points table
# Change table from wide to long
pts_game_df = pd.melt(point, id_vars = ['player','Team'],
                      var_name='games', value_name='points')
pts_game_df['games'] = pts_game_df['games'].str[5:6].astype('Int64')

pts_rnd_game_df = pd.merge(pts_game_df, game_rnd_team_df, on=['Team', 'games'])

pts_rnd_game_df

              player                 Team  games  points rnd
0           MW Short    Adelaide Strikers      1    41.0   1
1          SPD Smith        Sydney Sixers      1     NaN   1
2         GJ Maxwell      Melbourne Stars      1     NaN   1
3       W Sutherland  Melbourne Renegades      1    99.0   1
4          DA Warner       Sydney Thunder      1    17.0   1
...              ...                  ...    ...     ...  ..
1485  Mahli Beardman      Perth Scorchers      1   103.0   1
1486       TF Rogers      Melbourne Stars      1     9.0   1
1487   Will Salzmann       Sydney Thunder      1     NaN   1
1488    Xavier Crone  Melbourne Renegades      1     NaN   1
1489   Callum Vidler        Brisbane Heat      1     NaN   1

[1490 rows x 5 columns]

In [ ]:
# Points per round table

# Model Build

In [ ]:
# Three Models
# 1. Only one game; 2. Only two game; 3. Three or more game
# Features: 1 game lag, 2 game ma, 3 game ma, overall game average; 1 round lag, 2 round ma, 3 round ma, overall round average